### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by cybercat5555** [cybercat5555/Cybers-Ornate-Blocks#1]
- [ ] Placeable Ovis Atre Head using the Better Animals model

- [ ] Fix sounds for the Damask blocks, they should use the "cloth" sounds instead of stone sounds

- [ ] Add the second set of Damask blocks
